# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# è®¾ç½®å¯ç”¨çš„æ¨¡å—
format = "$all"

# Inserts a blank line between shell prompts
add_newline = true

# å„ç§è¯­è¨€é¡¹ç›®ç›®å½•ä¸‹çš„æ˜¾ç¤ºé…ç½®
[golang]
symbol = "ğŸ¦¦"
format = "Golang [$symbol($version )]($style)"

[nodejs]
format = "Node [$symbol($version )]($style)"

[lua]
format = "Lua [$symbol($version )]($style)"

[username]
show_always = true

[hostname]
ssh_only = false